GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO api;
GRANT ALL PRIVILEGES ON DATABASE fastapi TO api;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO root;
GRANT ALL PRIVILEGES ON DATABASE fastapi TO root;
